apiVersion: v1
kind: Pod
metadata:
  name: unexpected-binary
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args: ["cp /bin/ls /tmp/ls && /tmp/ls; sleep infinity"]
